config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'devise', skip: :registrations
  devise_scope :user do
    resource :registration, only: [:new, :create, :edit, :update], 
    path_names: {new: 'sign_up'},
    controller: 'devise/registrations',
    as: :user_registration do
      get :cancel
    end
  end

  resources :users, only:[:show]

  resource :cards
  resource :trades, only: [:create, :update, :show]
  root 'static_pages#trade_pool'
  get 'my_trades' => 'static_pages#trade_viewer' #for people
  get 'my_collection' => 'static_pages#my_collection' #for people
  get 'trade_pool' => 'static_pages#trade_pool' #for people
  get 'about' => 'static_pages#about' #for people
  get 'collection' => 'cards#fetch_collection' # for the component
  get 'pool' => 'cards#fetch_pool' # for the component
  get 'idle' => 'cards#fetch_idle' # for the component
  get 'pending' => 'cards#fetch_pending' # for the component
  patch 'cancel_trade' => 'trades#cancel_trade' # for component
  get 'active_trades' => 'trades#fetch_pending_trades' # for component
  patch 'accept' => 'trades#accept_trade' # for component
  get 'states/:country' => 'application#state_list'
  get 'successful_trades' => 'trades#fetch_successful_trades' # for component
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokéTrader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Lato|Averia+Libre" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
  <nav class="navbar navbar-inverse" id="navbar" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>   
        <%= link_to 'PokéTrader', root_path, class: 'navbar-brand' %>
      </div>   
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to(my_trades_path) do %>
                Trade Viewer <span id='badge' class='badge'><%=current_user.trade_count %></span>
              <% end %>
            </li>
            <li>
              <%= link_to 'My Profile', edit_user_registration_path %>
            </li>           
            <li>
              <%= link_to 'My Collection', my_collection_path %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', new_user_session_path %>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p class="navbar-text navbar-right">
            Hi, <%= current_user.username %>
          </p>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <% if flash[:error].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>

    <% if flash[:notice].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-info">
        <%= flash[:notice].html_safe %>
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class="col-xs-10 col-xs-offset-1 alert alert-warning">
        <%= flash[:alert].html_safe %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>